# Generated by Django 4.1.7 on 2023-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Usu_Documento', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='N° Documento')),
                ('Usu_Nombre', models.TextField(max_length=40)),
                ('Usu_Apellido', models.TextField(max_length=40)),
                ('Usu_tipo', models.TextField(max_length=40)),
                ('Usu_Celular', models.BigIntegerField(verbose_name='Numero De Celular')),
                ('Usu_Correo', models.EmailField(max_length=50, verbose_name='Correo Electronico')),
                ('Usu_Ficha', models.TextField(max_length=40)),
            ],
        ),
    ]
