# Generated by Django 4.1.7 on 2023-08-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0005_prestamos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='Pres_Equipos_id',
            new_name='Pres_Equipos',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Fec_Devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Hora_Devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Observaciones_recibido',
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Equ_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del equipo'),
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('San_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la sancion')),
                ('San_Fecha', models.DateField(auto_now=True)),
                ('San_Hora', models.TimeField(auto_now=True)),
                ('San_tiempo', models.BigIntegerField(verbose_name='Horas de la Sancion')),
                ('San_Descripcion', models.TextField(max_length=1000, verbose_name='Descripcion de la Sancion')),
                ('San_Pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.prestamos', verbose_name='Prestamo relacionado')),
            ],
        ),
    ]
