# Generated by Django 4.1.7 on 2023-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0006_rename_pres_equipos_id_prestamos_pres_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Equi_serial',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
