# Generated by Django 4.1.7 on 2023-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='Pres_Id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del prestamo'),
        ),
    ]
