# Generated by Django 4.1.7 on 2023-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('Equ_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID del equipo')),
                ('Equi_tipo', models.TextField(max_length=50)),
                ('Equi_modelo', models.TextField(max_length=50)),
                ('Equi_color', models.TextField(max_length=50)),
                ('Equi_serial', models.TextField(max_length=100)),
                ('Equi_estado', models.TextField(max_length=20)),
                ('equi_especialidad', models.TextField(max_length=50)),
            ],
        ),
    ]
