# Generated by Django 4.1.7 on 2023-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Usu_Celular',
            field=models.BigIntegerField(verbose_name='N° De Celular'),
        ),
    ]
