# Generated by Django 4.1.7 on 2023-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0003_alter_usuarios_usu_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Equ_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID del equipo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Usu_Documento',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='N° Documento'),
        ),
    ]
