# Generated by Django 4.1.7 on 2023-05-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0004_alter_equipos_equ_id_alter_usuarios_usu_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('Pres_Id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID del prestamo')),
                ('Pres_Fec_Entrega', models.DateField(auto_now=True)),
                ('Pres_Fec_Devolucion', models.DateField(auto_now=True)),
                ('Pres_Hora_Entrega', models.TimeField(auto_now=True, verbose_name='Hora de Entrega')),
                ('Pres_Hora_Devolucion', models.TimeField(auto_now=True, verbose_name='Hora de Devolucion')),
                ('Pres_Tiempo_Limite', models.BigIntegerField(verbose_name='Horas Que prestara el Equipo')),
                ('Pres_Observaciones_entrega', models.TextField(max_length=255, verbose_name='Observaciones Salida Equipo')),
                ('Pres_Observaciones_recibido', models.TextField(max_length=255, verbose_name='Observaciones Recibido')),
                ('Pres_Equipos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.equipos', verbose_name='ID del equipo')),
                ('Pres_Usuarios_Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.usuarios', verbose_name='N° Documento del usuario')),
            ],
        ),
    ]
