# Generated by Django 4.1.7 on 2023-05-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0006_sanciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanciones',
            name='id',
        ),
        migrations.AlterField(
            model_name='sanciones',
            name='San_Pres_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppInventario_ICED.prestamos', verbose_name='ID de la sancion'),
        ),
    ]
