# Generated by Django 4.1.7 on 2023-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0007_rename_pres_equipos_id_prestamos_pres_equipos_id_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='Pres_Equipos_id_id',
            new_name='Pres_Equipos',
        ),
        migrations.RenameField(
            model_name='prestamos',
            old_name='Pres_Usuarios_Documento_id',
            new_name='Pres_Usuarios_Documento',
        ),
    ]
