# Generated by Django 4.1.7 on 2023-07-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0008_rename_pres_equipos_id_id_prestamos_pres_equipos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanciones',
            old_name='San_Pres_Id',
            new_name='San_Pres',
        ),
    ]
