# Generated by Django 4.1.7 on 2023-07-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0009_rename_san_pres_id_sanciones_san_pres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Fec_Devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Hora_Devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='Pres_Observaciones_recibido',
        ),
    ]
