# Generated by Django 4.1.7 on 2023-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0010_remove_prestamos_pres_fec_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Equ_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID del equipo'),
        ),
    ]
