# Generated by Django 4.2 on 2023-10-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0011_historial_delete_devoluciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
