# Generated by Django 4.1.7 on 2023-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0011_alter_equipos_equ_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Equ_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID del equipo'),
        ),
    ]
