# Generated by Django 4.2 on 2023-10-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0012_delete_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('Pres_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pres_Fec_Entrega', models.DateField()),
                ('Pres_Hora_Entrega', models.TimeField()),
                ('Pres_Tiempo_Limite', models.BigIntegerField()),
                ('Pres_Observaciones_entrega', models.TextField(max_length=255)),
                ('Pres_Equipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.equipos')),
                ('Pres_Usuarios_Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.usuarios')),
            ],
        ),
    ]
