# Generated by Django 4.1.7 on 2023-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0015_alter_prestamos_pres_tiempo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='Pres_Tiempo_Limite',
            field=models.TextField(max_length=70),
        ),
    ]
