# Generated by Django 4.1.7 on 2023-10-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario_ICED', '0016_alter_historial_pres_tiempo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='Pres_Equipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario_ICED.equipos', to_field='Equi_serial', verbose_name='ID del equipo'),
        ),
    ]
